// <auto-generated />
using System;
using DataPatrolTask.DataMigration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataPatrolTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250713211759_SecondDataPortalMigration")]
    partial class SecondDataPortalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataPatrolTask.Models.PolicyAssignment", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PolicyId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("PolicyAssignments");
                });

            modelBuilder.Entity("DataPatrolTask.Models.PolicyTable", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyType")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.ToTable("PolicyTables");
                });

            modelBuilder.Entity("DataPatrolTask.Models.UserGroup", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("DataPatrolTask.Models.UserGroupMembership", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroupsMembership");
                });

            modelBuilder.Entity("DataPatrolTask.Models.UserInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("DataPatrolTask.Models.UserRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime?>("CompletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedUserUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestedUserUserId");

                    b.ToTable("UserRequests");
                });

            modelBuilder.Entity("DataPatrolTask.Models.PolicyAssignment", b =>
                {
                    b.HasOne("DataPatrolTask.Models.UserGroup", "Group")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataPatrolTask.Models.PolicyTable", "Policy")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("DataPatrolTask.Models.UserGroupMembership", b =>
                {
                    b.HasOne("DataPatrolTask.Models.UserGroup", "UserGroup")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataPatrolTask.Models.UserInfo", "User")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("DataPatrolTask.Models.UserRequest", b =>
                {
                    b.HasOne("DataPatrolTask.Models.UserInfo", "RequestedUser")
                        .WithMany("UserRequests")
                        .HasForeignKey("RequestedUserUserId");

                    b.Navigation("RequestedUser");
                });

            modelBuilder.Entity("DataPatrolTask.Models.PolicyTable", b =>
                {
                    b.Navigation("PolicyAssignments");
                });

            modelBuilder.Entity("DataPatrolTask.Models.UserGroup", b =>
                {
                    b.Navigation("PolicyAssignments");

                    b.Navigation("UserGroupMemberships");
                });

            modelBuilder.Entity("DataPatrolTask.Models.UserInfo", b =>
                {
                    b.Navigation("UserGroupMemberships");

                    b.Navigation("UserRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
